/*-------------------------------------------------------------*\
|DESCRIPTION: Final project: complex number matrix multiplier.	|
|AUTHOR: Alex Dierks											|
|DATE: May 6, 2019												|
\*-------------------------------------------------------------*/

#pragma warning (disable: 4996)

#include <stdio.h>
#include "Complex.h"

struct Complex add(const struct Complex* num1, const struct Complex* num2)
{
	struct Complex num;
	num.real = (*num1).real + (*num2).real;
	num.i = (*num1).i + (*num2).i;

	return num;
}

struct Complex subtract(const struct Complex* num1, const struct Complex* num2)
{
	struct Complex num;
	num.real = (*num1).real - (*num2).real;
	num.i = (*num1).i - (*num2).i;

	return num;
}

struct Complex multiply(const struct Complex* num1, const struct Complex* num2)
{
	struct Complex num;
	num.real = ((*num1).real * (*num2).real) - ((*num1).i * (*num2).i);
	num.i = ((*num1).real * (*num2).i) + ((*num1).i * (*num2).real);

	return num;
}

struct Complex divide(const struct Complex* num1, const struct Complex* num2)
{
	struct Complex num;
	long double r2 = (*num2).real;
	long double i2 = (*num2).i;
	long double r1 = (*num1).real;
	long double i1 = (*num1).i;


	if ((r2 == 0) && (i2 == 0))
	{
		num.real = 0;
		num.i = 0;
	}
	else
	{
		num.real = ((r1 * r2) + (i1 * i2)) / ((r2 * r2) + (i2 * i2));
		num.i = ((i1 * r2) - (r1 * i2)) / ((r2 * r2) + (i2 * i2));
	}
	
	return num;
}

/*Returns the structure generated by user input.*/
struct Complex read()
{
	struct Complex num;
	char c;
	scanf("%lf %lf%c", &num.real, &num.i, &c);
	return num;
}

void display(const struct Complex* num)
{
	printf("%lf%+lfi", (*num).real, (*num).i);
}

void displayln(const struct Complex* num)
{
	printf("%lf%+lfi\n", (*num).real, (*num).i);
}